releases:
  - name: "refactor(server): remove deprecated createFrameworkHandler API"
    packages:
      - name: "@sylphx/lens-server"
        bump: minor
      - name: "@sylphx/lens-next"
        bump: minor
      - name: "@sylphx/lens-fresh"
        bump: minor
      - name: "@sylphx/lens-solidstart"
        bump: minor
